console.log("  STUDENT REPORT CARD");
console.log("  *******************");
console.log ("   ");
let name = "Name : Ankita Mahanta";
console.log(name);
let school = "School name : Sri Aurobindo Institute of Integral Education";
console.log(school);
let section = "Section = A";
console.log(section);
let roll_no = "Roll No. = 4";
console.log(roll_no);
console.log("Marks of Subjects:-");
console.log ("   ");
console.log("Subjects    Marks");
console.log("~~~~~~~~    ~~~~~");
console.log("Math     :    93");
console.log("English  :    79");
console.log("Science  :    80");
let grade = "Grade = A";
console.log ("   ");
console.log(grade);